# language: node_js
# sudo: required
# node_js:
#   - lts/*
# install:
#   - yarn install # npm ci
# script:
#   - yarn docs:build
# deploy:
#   provider: pages
#   skip_cleanup: true
#   local_dir: docs/.vuepress/dist
#   github_token: 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 # GITHUB_TOKEN
#   keep_history: true
#   on:
#     branch: master

language: node_js
node_js:
  - 14
install:
  - npm install
script: npm run test